# Project information
site_name: hakushin-py
site_url: https://gh.seria.moe/hakushin-py
site_author: Seria Ati
site_description: Async API wrapper for hakush.in written in Python 

# Repository
repo_name: seriaati/hakushin-py
repo_url: https://github.com/seriaati/hakushin-py

# Copyright
copyright: Copyright &copy; 2025 - 2025 Seria Ati

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: black
      accent: black

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black
      accent: black

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: black
      accent: black

plugins:
  - search
  - social
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_toc_entry: false
            show_symbol_type_heading: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API Reference:
      - Clients:
          - Client: api_reference/clients/client.md
          - Genshin Impact: api_reference/clients/gi.md
          - Honkai Star Rail: api_reference/clients/hsr.md
          - Zenless Zone Zero: api_reference/clients/zzz.md
      - Models:
          - Models: api_reference/models/models.md
          - Genshin Impact: api_reference/models/gi.md
          - Honkai Star Rail: api_reference/models/hsr.md
          - Zenless Zone Zero: api_reference/models/zzz.md
      - Errors: api_reference/errors.md
      - Enums: api_reference/enums.md
      - Utils: api_reference/utils.md
