# Project information
site_name: hakushin-py
site_url: https://gh.seria.moe/hakushin-py
site_author: Seria Ati
site_description: Async API wrapper for hakush.in written in Python

# Repository
repo_name: seriaati/hakushin-py
repo_url: https://github.com/seriaati/hakushin-py

# Copyright
copyright: Copyright &copy; 2025 - 2025 Seria Ati

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: black
      accent: black

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black
      accent: black

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: black
      accent: black

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["hakushin"]
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://mkdocstrings.github.io/griffe/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
          options:
            backlinks: tree
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            parameter_headings: true
            relative_crossrefs: true
            scoped_crossrefs: true
            type_parameter_headings: true
            show_root_heading: true
            show_root_full_path: false
            show_root_toc_entry: false
            show_symbol_type_heading: true
            show_if_no_docstring: true
            show_source: false
            show_bases: false
            separate_signature: true
            signature_crossrefs: true
            show_symbol_type_toc: true
            show_signature_annotations: true
            show_signature_type_parameters: true
            summary: true
            filters:
              - "!^_"
            unwrap_annotated: true
            extensions:
              - griffe_pydantic:
                  schema: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API Reference:
      - Clients:
          - Client: api_reference/clients/client.md
          - Genshin Impact: api_reference/clients/gi.md
          - Honkai Star Rail: api_reference/clients/hsr.md
          - Zenless Zone Zero: api_reference/clients/zzz.md
      - Models:
          - Models: api_reference/models/models.md
          - Genshin Impact: api_reference/models/gi.md
          - Honkai Star Rail: api_reference/models/hsr.md
          - Zenless Zone Zero: api_reference/models/zzz.md
      - Errors: api_reference/errors.md
      - Enums: api_reference/enums.md
      - Utils: api_reference/utils.md
