name: Pytest

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Run tests
        run: uv run pytest