name: Run Pytest

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install poetry
        uses: Gr1N/setup-poetry@v8

      - name: Install dependencies
        run: poetry install --with test

      - name: Run pytest
        run: poetry run pytest