name: Pytest

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.4.16"

      - name: Run tests
        run: uv run -p 3.11 pytest